version: "3"

services:
  envoy:
    image: envoyproxy/envoy:dev-8d267ca634a21eb6b6922caa18dc69317ef4f65f
    ports:
      - "10000:10000" # Inbound endpoint
      - "8001:8001" # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./wasm/main.wasm:/etc/wasm/main.wasm
    networks:
      - envoy-merge-log
  helloworld:
    build: helloworldapp/
    ports: 
      - "8002:8002" # helloword is listen on the 
    networks:
      - envoy-merge-log

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    networks:
      - envoy-merge-log
    restart: on-failure
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - INTERACTIVESETUP_ENABLED=false
    depends_on:
      - elasticsearch


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    networks:
      - envoy-merge-log
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: on-failure
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - INTERACTIVESETUP_ENABLED=false
    volumes:
      - esenvoy:/usr/share/elasticsearch/data

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "14250:14250"
      - "9411:9411"
    networks:
      - envoy-merge-log
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: 
      - "--es.server-urls=http://elasticsearch:9200"
      - "--es.num-shards=1"
      - "--es.num-replicas=0"
      - "--log-level=error"
    depends_on:
      - elasticsearch

  jaeger-query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - envoy-merge-log
    restart: on-failure
    command: 
      - "--es.server-urls=http://elasticsearch:9200"
      - "--span-storage.type=elasticsearch"
    
    depends_on:
      - elasticsearch
volumes:
  esenvoy:
    driver: local

networks:
  envoy-merge-log:
    driver: bridge 


